 name: Build and Publish Snapshots

 on:
   push:
     branches-ignore:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@4
         with:
           ref: ${{ github.head_ref }}
           fetch-depth: 0

       - name: Set up the Java 21 environment
         uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '21'

       - run:
           ./mvnw clean compile



