 name: Build and Publish Snapshots

 on:
   push:
     branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4
       - name: Set up JDK 21
         uses: actions/setup-java@v3
         with:
           java-version: '21'
           distribution: 'zulu'
           cache: 'maven'
           server-id: publicshemas
           server-username: ${{ secrets.PUBLIC_SCHEMA_USER }}
           server-password: ${{ secrets.PUBLIC_SCHEMA_TOKEN }}
           settings-path: ${{ github.workspace }} # location for the settings.xml file

       - name: Build with Maven

         run: ./mvnw --batch-mode --update-snapshots --settings ./settings.xml compile
